### ISSUE TITLE
Add GRE-MTS protocol in the parameter checker

### ISSUE THREAD

**Issue by jcohenadad** [spine-generic/spine-generic#190]
GRE-MT0, GRE-MT1 and GRE-T1w are missing from the param checker.

**Comment by alexfoias** [comment]
The current implementation uses pybids. 

Unfortunately, since the BEP001 wasn't merged it, the MTS modality is not implemented in [config](https://github.com/bids-standard/pybids/blob/f9426cc240293478daee58e85181e0431fd4f2ef/bids/layout/config/bids.json ) for the structure. Therefore, we cannot look for MTS contrast in BIDSLayout, unless we fork pybids and add MTS. 

@jcohenadad How should we proceed ?

**Comment by jcohenadad** [comment]
> Unfortunately, since the BEP001 wasn't merged it, the MTS modality is not implemented in config for the structure. Therefore, we cannot look for MTS contrast in BIDSLayout, unless we fork pybids and add MTS.

ahhhhh that's a good reason 😉

**Comment by jcohenadad** [comment]
@alexfoias is there a possibility to point to a custom bids.json (instead of forking entirely)?

**Comment by alexfoias** [comment]
So what I have found to make it work is to add sg_layout_config.json . I'm currently implementing it. Useful documentation here: https://github.com/bids-standard/pybids/issues/584

**Comment by alexfoias** [comment]
One problem when trying to implement the conditions is that the presence of MTon pulse is different between vendors "ScanOptions": "PFF" (Philips), "ScanOptions": "MT" (Siemens Prisma fit), no ScanOption for GE. Also for MToff there's no flag for scan options, same for GRE-T1w.

I suggest we check the name of the file and TE,TR, FA as for the contrasts already implemented.
