### ISSUE TITLE
Inconsistency in labels in process_data.sh

### ISSUE THREAD

**Issue by valosekj** [spine-generic/spine-generic#223]
Here is stated that labels in the cord at C2 and C5 mid-vertebral levels will be created:
https://github.com/spine-generic/spine-generic/blob/7b4356333889fc0abee4f57cf733a09007244093/process_data.sh#L156-L157

But then actually, C3 and C5 labels are created:
https://github.com/spine-generic/spine-generic/blob/7b4356333889fc0abee4f57cf733a09007244093/process_data.sh#L71-L72

So, I think that line 156 should be corrected to C3 from C2.

**Comment by jcohenadad** [comment]
good catch @valosekj ! Actually, my suggestion would be to entirely remove the specifics at line 156 and just write "Create mid-vertebral levels in the cord (only if it does not exist)". I'm always in favour of minimizing duplications to avoid human error (such as this one 😉 ). e.g., if in the future we decide to update labels to be C2 and C7, we will need to update lines 71 and 156 instead of only one.
