### ISSUE TITLE
Update `process_data.sh` to be compatible with the latest datasets releases

### ISSUE THREAD

**Issue by valosekj** [spine-generic/spine-generic#274]
The [`process_data.sh` script](https://github.com/spine-generic/spine-generic/blob/master/process_data.sh) under the master branch (commit https://github.com/spine-generic/spine-generic/commit/bb09d74049fdda4043356f4157244e92cbeff06a) is currently incompatible with the latest release of the `data-multi-subject` dataset (`r20230223`: https://github.com/spine-generic/data-multi-subject/tree/r20230223).

Points to fix (not exhaustive list):

1. remove [`_rms`](https://github.com/spine-generic/spine-generic/blob/f6814fdb2028fe3d1a5d8a7bb60d38b9a447f5db/process_data.sh#L248), [`_RPI_r`](https://github.com/spine-generic/spine-generic/blob/f6814fdb2028fe3d1a5d8a7bb60d38b9a447f5db/process_data.sh#L152), etc suffixes from filenames because `.nii.gz` and `.json` files were renamed:

<img width="900" alt="image" src="https://github.com/spine-generic/spine-generic/assets/39456460/6f05ae4e-c91b-4520-afa5-b145411fc0cf">

2. update MTS filenames (suffixes updated in https://github.com/spine-generic/data-multi-subject/pull/135) -- related to https://github.com/spine-generic/spine-generic/issues/272
3. [fix atlas labels](https://github.com/spine-generic/spine-generic/issues/271)
4. make sure the `process_data.sh` script is also compatible with [data-single-subject](https://github.com/spine-generic/data-single-subject)

**Comment by renelabounek** [comment]
Some statistics:
`ls derivatives/labels/*/*/*T2w_seg-manual.nii.gz | wc -l   267`
`ls derivatives/labels/*/*/*T2star_seg-manual.nii.gz | wc -l  266`
`ls derivatives/labels/*/*/*T2star_gmseg-manual.nii.gz | wc -l  18`
`ls derivatives/labels/*/*/*T1w_seg-manual.nii.gz | wc -l  267`

Thus, I assume strings like **RPI_r** or **rms** should be removed from filenames of data_processed files.

Contrary, it means that proces_data.sh will never execute sct_deepseg_sc for T2w, T1w and almost never for T2star. And, qunatitative results will everytime be proportional to existing manual segmentations. So that raise the question: Do we want process_data.sh to behave that way everytime?

**Comment by renelabounek** [comment]
Utilizing existing _seg-manual, gmseg_manual and _labels_manual (commit [9cd6af1](https://github.com/spine-generic/spine-generic/pull/275/commits/9cd6af142d992e169cb6088e4c06223784d820b1)), the process_data.sh ended with error for following 7 scans:

sub-brnoUhb02 (T1w labeling)
sub-brnoUhb07 (T1w labeling)
sub-brnoUhb08 (T1w labeling)
sub-geneva01 (T1w labeling)
sub-oxfordFmrib04 (MTS analysis sct_register_multimodal)
sub-oxfordOhba02 (sct_dmri_moco)
sub-tokyoIngenia06 (T1W labeling)

Errors were related to T1w labeling in 5 cases, multimodal registration in MTS analysis in 1 case, and dMRI preprocessing in 1 case. I am going to check if segmentation fit the images in the 5 T1w files.

**Comment by renelabounek** [comment]
Processing of sub-brnoUhb scans fails due to mismatched T1w scan and its manual segmentation as reported [here](https://github.com/spine-generic/data-multi-subject/issues/153)
